
name: Scheduled Automation

on:
  push:
    branches:
      - main
  schedule:
    # First run: 9:20 AM IST (3:50 AM UTC)
    - cron: "50 3 * * 1-5"
    # Second run: 12:00 PM IST (6:30 AM UTC)
    - cron: "30 6 * * 1-5"

jobs:
  run-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # Set timeout to 3 hours
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y xvfb
        pip install undetected-chromedriver selenium mega.py bs4 requests pymongo pytz

    - name: Run Python script with virtual display
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' python file.py
